# Generated by Django 4.1.7 on 2023-08-23 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdictionaries',
            options={'verbose_name': 'User dictionaries'},
        ),
    ]
