# Generated by Django 4.1.7 on 2023-08-23 08:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_site', '0002_alter_userdictionaries_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDictionaries',
            new_name='User_Dictionaries',
        ),
    ]
