# Generated by Django 4.1.7 on 2023-08-23 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_site', '0005_delete_user_dictionaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Dictionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary', models.TextField(blank=True, verbose_name='Cловарь')),
                ('user', models.OneToOneField(default=0, max_length=191, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'User dictionaries',
            },
        ),
    ]
