# Generated by Django 4.1.7 on 2023-08-24 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_site', '0006_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Dictionaries',
            new_name='UserDictionaries',
        ),
        migrations.AlterModelOptions(
            name='userdictionaries',
            options={'verbose_name': 'Словари пользователей', 'verbose_name_plural': 'Словари пользователей'},
        ),
    ]
