# Generated by Django 4.1.7 on 2023-08-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0007_rename_user_dictionaries_userdictionaries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDictionaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=46, verbose_name='слово')),
                ('translation', models.CharField(max_length=26, verbose_name='перевод')),
            ],
        ),
    ]
