# Generated by Django 4.1.7 on 2023-08-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0008_masterdictionaries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masterdictionaries',
            options={'verbose_name': 'Слово в словарь', 'verbose_name_plural': 'Главный словарь'},
        ),
        migrations.AlterModelOptions(
            name='userdictionaries',
            options={'verbose_name': 'Словарь пользователея', 'verbose_name_plural': 'Словари пользователей'},
        ),
        migrations.AlterField(
            model_name='masterdictionaries',
            name='word',
            field=models.CharField(db_index=True, max_length=46, unique=True, verbose_name='слово'),
        ),
    ]
