# Generated by Django 4.1.7 on 2023-08-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0009_alter_masterdictionaries_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdictionaries',
            name='word',
            field=models.CharField(db_index=True, max_length=46, verbose_name='слово'),
        ),
    ]
