# Generated by Django 4.1.7 on 2023-08-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0010_alter_masterdictionaries_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdictionaries',
            name='translation',
            field=models.CharField(max_length=50, verbose_name='перевод'),
        ),
    ]
