# Generated by Django 4.1.7 on 2023-09-06 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0011_alter_masterdictionaries_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdictionaries',
            name='dictionary_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
