# Generated by Django 4.1.7 on 2023-09-06 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0012_userdictionaries_dictionary_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictionaries',
            name='dictionary_update',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 11, 16, 26, 222379, tzinfo=datetime.timezone.utc)),
        ),
    ]
