# Generated by Django 4.1.7 on 2023-09-06 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0013_alter_userdictionaries_dictionary_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictionaries',
            name='dictionary_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
