# Generated by Django 4.1.7 on 2023-10-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0016_alter_userdictionariesnew_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dateslastaddedwordinuserdict',
            options={'verbose_name': 'Дата полседнего добавления слова в словарь пользователя', 'verbose_name_plural': 'Даты полседнего добавления слова в словарь пользователей'},
        ),
    ]
