# Generated by Django 4.1.7 on 2023-10-04 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_site', '0017_alter_dateslastaddedwordinuserdict_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateslastaddedwordinuserdict',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
