# Generated by Django 4.1.7 on 2023-10-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0018_alter_dateslastaddedwordinuserdict_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDictionaries',
        ),
    ]
