# Generated by Django 4.1.7 on 2023-10-05 09:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base_site', '0019_delete_userdictionaries'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDictionariesNew',
            new_name='UserDictionaries',
        ),
    ]
