# Generated by Django 4.1.7 on 2023-10-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0020_rename_userdictionariesnew_userdictionaries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdictionaries',
            options={'ordering': ['last_training_result', '-last_training_date'], 'verbose_name': 'Словарь пользователя', 'verbose_name_plural': 'Словари пользователей'},
        ),
    ]
