# Generated by Django 4.1.7 on 2023-10-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0021_alter_userdictionaries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateslastaddedwordinuserdict',
            name='date_last_added_word',
            field=models.DateTimeField(verbose_name='последнее слово добавлено'),
        ),
    ]
