# Generated by Django 4.1.7 on 2023-10-23 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0023_alter_userdictionaries_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdictionaries',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_site.masterdictionaries'),
        ),
    ]
